
import struct

#
#   LUIDs for built-in layers.
#
#   cf. Windows Kits\10\Include\10.0.15063.0\km\fwpsk.h
#

FWPS_LAYER_INBOUND_IPPACKET_V4				= 0
FWPS_LAYER_INBOUND_IPPACKET_V4_DISCARD			= 1
FWPS_LAYER_INBOUND_IPPACKET_V6				= 2
FWPS_LAYER_INBOUND_IPPACKET_V6_DISCARD			= 3
FWPS_LAYER_OUTBOUND_IPPACKET_V4				= 4
FWPS_LAYER_OUTBOUND_IPPACKET_V4_DISCARD			= 5
FWPS_LAYER_OUTBOUND_IPPACKET_V6				= 6
FWPS_LAYER_OUTBOUND_IPPACKET_V6_DISCARD			= 7
FWPS_LAYER_IPFORWARD_V4					= 8
FWPS_LAYER_IPFORWARD_V4_DISCARD				= 9
FWPS_LAYER_IPFORWARD_V6					= 10
FWPS_LAYER_IPFORWARD_V6_DISCARD				= 11
FWPS_LAYER_INBOUND_TRANSPORT_V4				= 12
FWPS_LAYER_INBOUND_TRANSPORT_V4_DISCARD			= 13
FWPS_LAYER_INBOUND_TRANSPORT_V6				= 14
FWPS_LAYER_INBOUND_TRANSPORT_V6_DISCARD			= 15
FWPS_LAYER_OUTBOUND_TRANSPORT_V4			= 16
FWPS_LAYER_OUTBOUND_TRANSPORT_V4_DISCARD		= 17
FWPS_LAYER_OUTBOUND_TRANSPORT_V6			= 18
FWPS_LAYER_OUTBOUND_TRANSPORT_V6_DISCARD		= 19
FWPS_LAYER_STREAM_V4					= 20
FWPS_LAYER_STREAM_V4_DISCARD				= 21
FWPS_LAYER_STREAM_V6					= 22
FWPS_LAYER_STREAM_V6_DISCARD				= 23
FWPS_LAYER_DATAGRAM_DATA_V4				= 24
FWPS_LAYER_DATAGRAM_DATA_V4_DISCARD			= 25
FWPS_LAYER_DATAGRAM_DATA_V6				= 26
FWPS_LAYER_DATAGRAM_DATA_V6_DISCARD			= 27
FWPS_LAYER_INBOUND_ICMP_ERROR_V4			= 28
FWPS_LAYER_INBOUND_ICMP_ERROR_V4_DISCARD		= 29
FWPS_LAYER_INBOUND_ICMP_ERROR_V6			= 30
FWPS_LAYER_INBOUND_ICMP_ERROR_V6_DISCARD		= 31
FWPS_LAYER_OUTBOUND_ICMP_ERROR_V4			= 32
FWPS_LAYER_OUTBOUND_ICMP_ERROR_V4_DISCARD		= 33
FWPS_LAYER_OUTBOUND_ICMP_ERROR_V6			= 34
FWPS_LAYER_OUTBOUND_ICMP_ERROR_V6_DISCARD		= 35
FWPS_LAYER_ALE_RESOURCE_ASSIGNMENT_V4			= 36
FWPS_LAYER_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD	        = 37
FWPS_LAYER_ALE_RESOURCE_ASSIGNMENT_V6			= 38
FWPS_LAYER_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD	        = 39
FWPS_LAYER_ALE_AUTH_LISTEN_V4				= 40
FWPS_LAYER_ALE_AUTH_LISTEN_V4_DISCARD			= 41
FWPS_LAYER_ALE_AUTH_LISTEN_V6				= 42
FWPS_LAYER_ALE_AUTH_LISTEN_V6_DISCARD			= 43
FWPS_LAYER_ALE_AUTH_RECV_ACCEPT_V4			= 44
FWPS_LAYER_ALE_AUTH_RECV_ACCEPT_V4_DISCARD		= 45
FWPS_LAYER_ALE_AUTH_RECV_ACCEPT_V6			= 46
FWPS_LAYER_ALE_AUTH_RECV_ACCEPT_V6_DISCARD		= 47
FWPS_LAYER_ALE_AUTH_CONNECT_V4				= 48
FWPS_LAYER_ALE_AUTH_CONNECT_V4_DISCARD			= 49
FWPS_LAYER_ALE_AUTH_CONNECT_V6				= 50
FWPS_LAYER_ALE_AUTH_CONNECT_V6_DISCARD			= 51
FWPS_LAYER_ALE_FLOW_ESTABLISHED_V4			= 52
FWPS_LAYER_ALE_FLOW_ESTABLISHED_V4_DISCARD		= 53
FWPS_LAYER_ALE_FLOW_ESTABLISHED_V6			= 54
FWPS_LAYER_ALE_FLOW_ESTABLISHED_V6_DISCARD		= 55
FWPS_LAYER_INBOUND_MAC_FRAME_ETHERNET			= 56
FWPS_LAYER_OUTBOUND_MAC_FRAME_ETHERNET			= 57
# 58 59 ...
FWPS_LAYER_NAME_RESOLUTION_CACHE_V4			= 60
FWPS_LAYER_NAME_RESOLUTION_CACHE_V6			= 61   
FWPS_LAYER_ALE_RESOURCE_RELEASE_V4			= 62
FWPS_LAYER_ALE_RESOURCE_RELEASE_V6			= 63
FWPS_LAYER_ALE_ENDPOINT_CLOSURE_V4			= 64
FWPS_LAYER_ALE_ENDPOINT_CLOSURE_V6			= 65
FWPS_LAYER_ALE_CONNECT_REDIRECT_V4			= 66
FWPS_LAYER_ALE_CONNECT_REDIRECT_V6			= 67
FWPS_LAYER_ALE_BIND_REDIRECT_V4				= 68
FWPS_LAYER_ALE_BIND_REDIRECT_V6				= 69
FWPS_LAYER_STREAM_PACKET_V4				= 70
FWPS_LAYER_STREAM_PACKET_V6				= 71
FWPS_LAYER_INGRESS_VSWITCH_ETHERNET			= 72
FWPS_LAYER_EGRESS_VSWITCH_ETHERNET			= 73
FWPS_LAYER_INGRESS_VSWITCH_TRANSPORT_V4			= 74
FWPS_LAYER_INGRESS_VSWITCH_TRANSPORT_V6			= 75
FWPS_LAYER_EGRESS_VSWITCH_TRANSPORT_V4			= 76
FWPS_LAYER_EGRESS_VSWITCH_TRANSPORT_V6			= 77
FWPS_LAYER_INBOUND_TRANSPORT_FAST			= 78
FWPS_LAYER_OUTBOUND_TRANSPORT_FAST			= 79   
FWPS_LAYER_INBOUND_MAC_FRAME_NATIVE_FAST		= 80
FWPS_LAYER_OUTBOUND_MAC_FRAME_NATIVE_FAST		= 81
FWPS_LAYER_ALE_PRECLASSIFY_IP_LOCAL_ADDRESS_V4	        = 82
FWPS_LAYER_ALE_PRECLASSIFY_IP_REMOTE_ADDRESS_V4	        = 83
FWPS_LAYER_ALE_PRECLASSIFY_IP_LOCAL_PORT_V4		= 84
FWPS_LAYER_ALE_PRECLASSIFY_IP_REMOTE_PORT_V4		= 85
FWPS_LAYER_ALE_PRECLASSIFY_IP_LOCAL_ADDRESS_V6	        = 86
FWPS_LAYER_ALE_PRECLASSIFY_IP_REMOTE_ADDRESS_V6	        = 87              
FWPS_LAYER_ALE_PRECLASSIFY_IP_LOCAL_PORT_V6		= 88
FWPS_LAYER_ALE_PRECLASSIFY_IP_REMOTE_PORT_V6		= 89
FWPS_LAYER_IPSEC_KM_DEMUX_V4				= 90
FWPS_LAYER_IPSEC_KM_DEMUX_V6				= 91
FWPS_LAYER_IPSEC_V4					= 92
FWPS_LAYER_IPSEC_V6					= 93
FWPS_LAYER_IKEEXT_V4					= 94
FWPS_LAYER_IKEEXT_V6					= 95                                       
FWPS_LAYER_RPC_UM					= 96
FWPS_LAYER_RPC_EPMAP					= 97
FWPS_LAYER_RPC_EP_ADD					= 98
FWPS_LAYER_RPC_PROXY_CONN				= 99
FWPS_LAYER_RPC_PROXY_IF					= 100
FWPS_LAYER_KM_AUTHORIZATION				= 101
FWPS_BUILTIN_LAYER_MAX					= 102

FWPS_layerId_to_str = [
    'FWPS_LAYER_INBOUND_IPPACKET_V4',			
    'FWPS_LAYER_INBOUND_IPPACKET_V4_DISCARD',		
    'FWPS_LAYER_INBOUND_IPPACKET_V6',			
    'FWPS_LAYER_INBOUND_IPPACKET_V6_DISCARD',			
    'FWPS_LAYER_OUTBOUND_IPPACKET_V4',			
    'FWPS_LAYER_OUTBOUND_IPPACKET_V4_DISCARD',			
    'FWPS_LAYER_OUTBOUND_IPPACKET_V6',				
    'FWPS_LAYER_OUTBOUND_IPPACKET_V6_DISCARD',			
    'FWPS_LAYER_IPFORWARD_V4',			
    'FWPS_LAYER_IPFORWARD_V4_DISCARD',				
    'FWPS_LAYER_IPFORWARD_V6',				
    'FWPS_LAYER_IPFORWARD_V6_DISCARD',				
    'FWPS_LAYER_INBOUND_TRANSPORT_V4',				
    'FWPS_LAYER_INBOUND_TRANSPORT_V4_DISCARD',			
    'FWPS_LAYER_INBOUND_TRANSPORT_V6',			
    'FWPS_LAYER_INBOUND_TRANSPORT_V6_DISCARD',			
    'FWPS_LAYER_OUTBOUND_TRANSPORT_V4',		
    'FWPS_LAYER_OUTBOUND_TRANSPORT_V4_DISCARD',		
    'FWPS_LAYER_OUTBOUND_TRANSPORT_V6',		
    'FWPS_LAYER_OUTBOUND_TRANSPORT_V6_DISCARD',		
    'FWPS_LAYER_STREAM_V4',			
    'FWPS_LAYER_STREAM_V4_DISCARD',		
    'FWPS_LAYER_STREAM_V6',				
    'FWPS_LAYER_STREAM_V6_DISCARD',				
    'FWPS_LAYER_DATAGRAM_DATA_V4',				
    'FWPS_LAYER_DATAGRAM_DATA_V4_DISCARD',			
    'FWPS_LAYER_DATAGRAM_DATA_V6',			
    'FWPS_LAYER_DATAGRAM_DATA_V6_DISCARD',			
    'FWPS_LAYER_INBOUND_ICMP_ERROR_V4',		
    'FWPS_LAYER_INBOUND_ICMP_ERROR_V4_DISCARD',		
    'FWPS_LAYER_INBOUND_ICMP_ERROR_V6',		
    'FWPS_LAYER_INBOUND_ICMP_ERROR_V6_DISCARD',		
    'FWPS_LAYER_OUTBOUND_ICMP_ERROR_V4',		
    'FWPS_LAYER_OUTBOUND_ICMP_ERROR_V4_DISCARD',		
    'FWPS_LAYER_OUTBOUND_ICMP_ERROR_V6',	
    'FWPS_LAYER_OUTBOUND_ICMP_ERROR_V6_DISCARD',		
    'FWPS_LAYER_ALE_RESOURCE_ASSIGNMENT_V4',		
    'FWPS_LAYER_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD',	        
    'FWPS_LAYER_ALE_RESOURCE_ASSIGNMENT_V6',		
    'FWPS_LAYER_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD',	        
    'FWPS_LAYER_ALE_AUTH_LISTEN_V4',		
    'FWPS_LAYER_ALE_AUTH_LISTEN_V4_DISCARD',	
    'FWPS_LAYER_ALE_AUTH_LISTEN_V6',			
    'FWPS_LAYER_ALE_AUTH_LISTEN_V6_DISCARD',			
    'FWPS_LAYER_ALE_AUTH_RECV_ACCEPT_V4',		
    'FWPS_LAYER_ALE_AUTH_RECV_ACCEPT_V4_DISCARD',		
    'FWPS_LAYER_ALE_AUTH_RECV_ACCEPT_V6',	
    'FWPS_LAYER_ALE_AUTH_RECV_ACCEPT_V6_DISCARD',
    'FWPS_LAYER_ALE_AUTH_CONNECT_V4',		
    'FWPS_LAYER_ALE_AUTH_CONNECT_V4_DISCARD',	
    'FWPS_LAYER_ALE_AUTH_CONNECT_V6',			
    'FWPS_LAYER_ALE_AUTH_CONNECT_V6_DISCARD',			
    'FWPS_LAYER_ALE_FLOW_ESTABLISHED_V4',		
    'FWPS_LAYER_ALE_FLOW_ESTABLISHED_V4_DISCARD',		
    'FWPS_LAYER_ALE_FLOW_ESTABLISHED_V6',	
    'FWPS_LAYER_ALE_FLOW_ESTABLISHED_V6_DISCARD',
    'FWPS_LAYER_INBOUND_MAC_FRAME_ETHERNET',		
    'FWPS_LAYER_OUTBOUND_MAC_FRAME_ETHERNET',
    '', # 58
    '', # 59
    'FWPS_LAYER_NAME_RESOLUTION_CACHE_V4',			
    'FWPS_LAYER_NAME_RESOLUTION_CACHE_V6',			   
    'FWPS_LAYER_ALE_RESOURCE_RELEASE_V4',		
    'FWPS_LAYER_ALE_RESOURCE_RELEASE_V6',		
    'FWPS_LAYER_ALE_ENDPOINT_CLOSURE_V4',		
    'FWPS_LAYER_ALE_ENDPOINT_CLOSURE_V6',		
    'FWPS_LAYER_ALE_CONNECT_REDIRECT_V4',		
    'FWPS_LAYER_ALE_CONNECT_REDIRECT_V6',		
    'FWPS_LAYER_ALE_BIND_REDIRECT_V4',			
    'FWPS_LAYER_ALE_BIND_REDIRECT_V6',				
    'FWPS_LAYER_STREAM_PACKET_V4',				
    'FWPS_LAYER_STREAM_PACKET_V6',				
    'FWPS_LAYER_INGRESS_VSWITCH_ETHERNET',			
    'FWPS_LAYER_EGRESS_VSWITCH_ETHERNET',		
    'FWPS_LAYER_INGRESS_VSWITCH_TRANSPORT_V4',			
    'FWPS_LAYER_INGRESS_VSWITCH_TRANSPORT_V6',			
    'FWPS_LAYER_EGRESS_VSWITCH_TRANSPORT_V4',			
    'FWPS_LAYER_EGRESS_VSWITCH_TRANSPORT_V6',			
    'FWPS_LAYER_INBOUND_TRANSPORT_FAST',		
    'FWPS_LAYER_OUTBOUND_TRANSPORT_FAST',		   
    'FWPS_LAYER_INBOUND_MAC_FRAME_NATIVE_FAST',		
    'FWPS_LAYER_OUTBOUND_MAC_FRAME_NATIVE_FAST',		
    'FWPS_LAYER_ALE_PRECLASSIFY_IP_LOCAL_ADDRESS_V4',	        
    'FWPS_LAYER_ALE_PRECLASSIFY_IP_REMOTE_ADDRESS_V4',	        
    'FWPS_LAYER_ALE_PRECLASSIFY_IP_LOCAL_PORT_V4',		
    'FWPS_LAYER_ALE_PRECLASSIFY_IP_REMOTE_PORT_V4',		
    'FWPS_LAYER_ALE_PRECLASSIFY_IP_LOCAL_ADDRESS_V6',	        
    'FWPS_LAYER_ALE_PRECLASSIFY_IP_REMOTE_ADDRESS_V6',	                      
    'FWPS_LAYER_ALE_PRECLASSIFY_IP_LOCAL_PORT_V6',		
    'FWPS_LAYER_ALE_PRECLASSIFY_IP_REMOTE_PORT_V6',
    'FWPS_LAYER_IPSEC_KM_DEMUX_V4',		
    'FWPS_LAYER_IPSEC_KM_DEMUX_V6',		
    'FWPS_LAYER_IPSEC_V4',		
    'FWPS_LAYER_IPSEC_V6',					
    'FWPS_LAYER_IKEEXT_V4',					
    'FWPS_LAYER_IKEEXT_V6',					                                       
    'FWPS_LAYER_RPC_UM',				
    'FWPS_LAYER_RPC_EPMAP',					
    'FWPS_LAYER_RPC_EP_ADD',					
    'FWPS_LAYER_RPC_PROXY_CONN',				
    'FWPS_LAYER_RPC_PROXY_IF',				
    'FWPS_LAYER_KM_AUTHORIZATION',				
    'FWPS_BUILTIN_LAYER_MAX'
]

FWPM_layerGuid_to_layerIdStr = {
    # 'FWPM_LAYER_INBOUND_IPPACKET_V4',			
    # 'FWPM_LAYER_INBOUND_IPPACKET_V4_DISCARD',		
    # 'FWPM_LAYER_INBOUND_IPPACKET_V6',			
    # 'FWPM_LAYER_INBOUND_IPPACKET_V6_DISCARD',			
    # 'FWPM_LAYER_OUTBOUND_IPPACKET_V4',			
    # 'FWPM_LAYER_OUTBOUND_IPPACKET_V4_DISCARD',			
    # 'FWPM_LAYER_OUTBOUND_IPPACKET_V6',				
    # 'FWPM_LAYER_OUTBOUND_IPPACKET_V6_DISCARD',			
    'a82acc24-4ee1-4ee1-b465-fd1d25cb10a4' : 'FWPM_LAYER_IPFORWARD_V4',
    # 'FWPM_LAYER_IPFORWARD_V4_DISCARD',				
    # 'FWPM_LAYER_IPFORWARD_V6',
    '7b964818-19c7-493a-b71f-832c3684d28c' : 'FWPM_LAYER_IPFORWARD_V6',
    # 'FWPM_LAYER_IPFORWARD_V6_DISCARD',				
    '5926dfc8-e3cf-4426-a283-dc393f5d0f9d' : 'FWPM_LAYER_INBOUND_TRANSPORT_V4',				
    'ac4a9833-f69d-4648-b261-6dc84835ef39' : 'FWPM_LAYER_INBOUND_TRANSPORT_V4_DISCARD',			
    '634a869f-fc23-4b90-b0c1-bf620a36ae6f' : 'FWPM_LAYER_INBOUND_TRANSPORT_V6',			
    '2a6ff955-3b2b-49d2-9848-ad9d72dcaab7' : 'FWPM_LAYER_INBOUND_TRANSPORT_V6_DISCARD',			
    '09e61aea-d214-46e2-9b21-b26b0b2f28c8' : 'FWPM_LAYER_OUTBOUND_TRANSPORT_V4',		
    # 'FWPM_LAYER_OUTBOUND_TRANSPORT_V4_DISCARD',		
    'e1735bde-013f-4655-b351-a49e15762df0' : 'FWPM_LAYER_OUTBOUND_TRANSPORT_V6',		
    # 'FWPM_LAYER_OUTBOUND_TRANSPORT_V6_DISCARD',		
    '3b89653c-c170-49e4-b1cd-e0eeeee19a3e' : 'FWPM_LAYER_STREAM_V4',			
    # 'FWPM_LAYER_STREAM_V4_DISCARD',		
    '47c9137a-7ec4-46b3-b6e4-48e926b1eda4' : 'FWPM_LAYER_STREAM_V6',				
    # 'FWPM_LAYER_STREAM_V6_DISCARD',				
    '3d08bf4e-45f6-4930-a922-417098e20027' : 'FWPM_LAYER_DATAGRAM_DATA_V4',				
    # 'FWPM_LAYER_DATAGRAM_DATA_V4_DISCARD',			
    'fa45fe2f-3cba-4427-87fc-57b9a4b10d00' : 'FWPM_LAYER_DATAGRAM_DATA_V6',			
    # 'FWPM_LAYER_DATAGRAM_DATA_V6_DISCARD',			
    # 'FWPM_LAYER_INBOUND_ICMP_ERROR_V4',
    '61499990-3cb6-4e84-b950-53b94b6964f3' : 'FWPM_LAYER_INBOUND_ICMP_ERROR_V4',
    # 'FWPM_LAYER_INBOUND_ICMP_ERROR_V4_DISCARD',
    '65f9bdff-3b2d-4e5d-b8c6-c720651fe898' : 'FWPM_LAYER_INBOUND_ICMP_ERROR_V6',
    # 'FWPM_LAYER_INBOUND_ICMP_ERROR_V6_DISCARD',		
    '41390100-564c-4b32-bc1d-718048354d7c' : 'FWPM_LAYER_OUTBOUND_ICMP_ERROR_V4',		
    # 'FWPM_LAYER_OUTBOUND_ICMP_ERROR_V4_DISCARD',		
    '7fb03b60-7b8d-4dfa-badd-980176fc4e12' : 'FWPM_LAYER_OUTBOUND_ICMP_ERROR_V6',
    # 'FWPM_LAYER_OUTBOUND_ICMP_ERROR_V6_DISCARD',		
    '1247d66d-0b60-4a15-8d44-7155d0f53a0c' : 'FWPM_LAYER_ALE_RESOURCE_ASSIGNMENT_V4',		
    '0b5812a2-c3ff-4eca-b88d-c79e20ac6322' : 'FWPM_LAYER_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD',	        
    '55a650e1-5f0a-4eca-a653-88f53b26aa8c' : 'FWPM_LAYER_ALE_RESOURCE_ASSIGNMENT_V6',		
    'cbc998bb-c51f-4c1a-bb4f-9775fcacab2f' : 'FWPM_LAYER_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD',	        
    '88bb5dad-76d7-4227-9c71-df0a3ed7be7e' : 'FWPM_LAYER_ALE_AUTH_LISTEN_V4',		
    '371dfada-9f26-45fd-b4eb-c29eb212893f' : 'FWPM_LAYER_ALE_AUTH_LISTEN_V4_DISCARD',	
    '7ac9de24-17dd-4814-b4bd-a9fbc95a321b' : 'FWPM_LAYER_ALE_AUTH_LISTEN_V6',			
    '60703b07-63c8-48e9-ada3-12b1af40a617' : 'FWPM_LAYER_ALE_AUTH_LISTEN_V6_DISCARD',			
    'e1cd9fe7-f4b5-4273-96c0-592e487b8650' : 'FWPM_LAYER_ALE_AUTH_RECV_ACCEPT_V4',		
    '9eeaa99b-bd22-4227-919f-0073c63357b1' : 'FWPM_LAYER_ALE_AUTH_RECV_ACCEPT_V4_DISCARD',
    'a3b42c97-9f04-4672-b87e-cee9c483257f' : 'FWPM_LAYER_ALE_AUTH_RECV_ACCEPT_V6',	
    '89455b97-dbe1-453f-a224-13da895af396' : 'FWPM_LAYER_ALE_AUTH_RECV_ACCEPT_V6_DISCARD',
    'c38d57d1-05a7-4c33-904f-7fbceee60e82' : 'FWPM_LAYER_ALE_AUTH_CONNECT_V4',		
    'd632a801-f5ba-4ad6-96e3-607017d9836a' : 'FWPM_LAYER_ALE_AUTH_CONNECT_V4_DISCARD',	
    '4a72393b-319f-44bc-84c3-ba54dcb3b6b4' : 'FWPM_LAYER_ALE_AUTH_CONNECT_V6',			
    'c97bc3b8-c9a3-4e33-8695-8e17aad4de09' : 'FWPM_LAYER_ALE_AUTH_CONNECT_V6_DISCARD',			
    'af80470a-5596-4c13-9992-539e6fe57967' : 'FWPM_LAYER_ALE_FLOW_ESTABLISHED_V4',		
    '146ae4a9-a1d2-4d43-a31a-4c42682b8e4f' : 'FWPM_LAYER_ALE_FLOW_ESTABLISHED_V4_DISCARD',		
    '7021d2b3-dfa4-406e-afeb-6afaf7e70efd' : 'FWPM_LAYER_ALE_FLOW_ESTABLISHED_V6',	
    '46928636-bbca-4b76-941d-0fa7f5d7d372' : 'FWPM_LAYER_ALE_FLOW_ESTABLISHED_V6_DISCARD',
    # 'FWPM_LAYER_INBOUND_MAC_FRAME_ETHERNET',		
    # 'FWPM_LAYER_OUTBOUND_MAC_FRAME_ETHERNET',			
    # 'FWPM_LAYER_NAME_RESOLUTION_CACHE_V4',			
    # 'FWPM_LAYER_NAME_RESOLUTION_CACHE_V6',			   
    '74365cce-ccb0-401a-bfc1-b89934ad7e15' : 'FWPM_LAYER_ALE_RESOURCE_RELEASE_V4',		
    'f4e5ce80-edcc-4e13-8a2f-b91454bb057b' : 'FWPM_LAYER_ALE_RESOURCE_RELEASE_V6',		
    'b4766427-e2a2-467a-bd7e-dbcd1bd85a09' : 'FWPM_LAYER_ALE_ENDPOINT_CLOSURE_V4',		
    'bb536ccd-4755-4ba9-9ff7-f9edf8699c7b' : 'FWPM_LAYER_ALE_ENDPOINT_CLOSURE_V6',		
    'c6e63c8c-b784-4562-aa7d-0a67cfcaf9a3' : 'FWPM_LAYER_ALE_CONNECT_REDIRECT_V4',		
    '587e54a7-8046-42ba-a0aa-b716250fc7fd' : 'FWPM_LAYER_ALE_CONNECT_REDIRECT_V6',		
    # 'FWPM_LAYER_ALE_BIND_REDIRECT_V4',			
    # 'FWPM_LAYER_ALE_BIND_REDIRECT_V6',				
    # 'FWPM_LAYER_STREAM_PACKET_V4',				
    # 'FWPM_LAYER_STREAM_PACKET_V6',				
    # 'FWPM_LAYER_INGRESS_VSWITCH_ETHERNET',			
    # 'FWPM_LAYER_EGRESS_VSWITCH_ETHERNET',		
    # 'FWPM_LAYER_INGRESS_VSWITCH_TRANSPORT_V4',			
    # 'FWPM_LAYER_INGRESS_VSWITCH_TRANSPORT_V6',			
    # 'FWPM_LAYER_EGRESS_VSWITCH_TRANSPORT_V4',			
    # 'FWPM_LAYER_EGRESS_VSWITCH_TRANSPORT_V6',			
    # 'FWPM_LAYER_INBOUND_TRANSPORT_FAST',		
    # 'FWPM_LAYER_OUTBOUND_TRANSPORT_FAST',		   
    # 'FWPM_LAYER_INBOUND_MAC_FRAME_NATIVE_FAST',		
    # 'FWPM_LAYER_OUTBOUND_MAC_FRAME_NATIVE_FAST',		
    # 'FWPM_LAYER_ALE_PRECLASSIFY_IP_LOCAL_ADDRESS_V4',	        
    # 'FWPM_LAYER_ALE_PRECLASSIFY_IP_REMOTE_ADDRESS_V4',	        
    # 'FWPM_LAYER_ALE_PRECLASSIFY_IP_LOCAL_PORT_V4',		
    # 'FWPM_LAYER_ALE_PRECLASSIFY_IP_REMOTE_PORT_V4',		
    # 'FWPM_LAYER_ALE_PRECLASSIFY_IP_LOCAL_ADDRESS_V6',	        
    # 'FWPM_LAYER_ALE_PRECLASSIFY_IP_REMOTE_ADDRESS_V6',	                      
    # 'FWPM_LAYER_ALE_PRECLASSIFY_IP_LOCAL_PORT_V6',		
    # 'FWPM_LAYER_ALE_PRECLASSIFY_IP_REMOTE_PORT_V6',
    # 'FWPM_LAYER_IPSEC_KM_DEMUX_V4',		
    # 'FWPM_LAYER_IPSEC_KM_DEMUX_V6',		
    # 'FWPM_LAYER_IPSEC_V4',		
    # 'FWPM_LAYER_IPSEC_V6',					
    # 'FWPM_LAYER_IKEEXT_V4',					
    # 'FWPM_LAYER_IKEEXT_V6',					                                       
    # 'FWPM_LAYER_RPC_UM',				
    # 'FWPM_LAYER_RPC_EPMAP',					
    # 'FWPM_LAYER_RPC_EP_ADD',					
    # 'FWPM_LAYER_RPC_PROXY_CONN',				
    # 'FWPM_LAYER_RPC_PROXY_IF',				
    # 'FWPM_LAYER_KM_AUTHORIZATION',				
    # 'FWPM_BUILTIN_LAYER_MAX'
}

FWPM_fieldGuid_to_fieldIdStr = {
    '511166dc-7a8c-4aa7-b533-95ab59fb0340' : 'FWPM_CONDITION_ARRIVAL_TUNNEL_TYPE',
    '89f990de-e798-4e6d-ab76-7c9558292e6f' : 'FWPM_CONDITION_ARRIVAL_INTERFACE_TYPE',
    '8784c146-ca97-44d6-9fd1-19fb1840cbf7' : 'FWPM_CONDITION_DIRECTION',
    'c35a604d-d22b-4e1a-91b4-68f674ee674b' : 'FWPM_CONDITION_IP_REMOTE_PORT',
    '3971ef2b-623e-4f9a-8cb1-6e79b806b9a7' : 'FWPM_CONDITION_IP_PROTOCOL',
    '0c1ba1af-5765-453f-af22-a8f791ac775b' : 'FWPM_CONDITION_IP_LOCAL_PORT',
    '632ce23b-5167-435c-86d7-e903684aa80c' : 'FWPM_CONDITION_FLAGS',
    '71bc78fa-f17c-4997-a602-6abb261f351c' : 'FWPM_CONDITION_ALE_PACKAGE_ID',
    'd78e1e87-8644-4ea5-9437-d809ecefc971' : 'FWPM_CONDITION_ALE_APP_ID',
    'b235ae9a-1d64-49b8-a44c-5ff3d9095045' : 'FWPM_CONDITION_IP_REMOTE_ADDRESS',
    '97537c6c-d9a3-4767-a381-e942675cd920' : 'FWPM_CONDITION_NEXTHOP_INTERFACE_TYPE',
    # ...
}

#
#   LUIDs for built-in fields.
#
#   cf. Windows Kits\10\Include\10.0.15063.0\km\fwpsk.h
#

FWPS_layerId_to_fieldIdsStr = {
    FWPS_LAYER_ALE_AUTH_CONNECT_V4 : [
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_ALE_APP_ID',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_ALE_USER_ID',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_IP_PROTOCOL',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_IP_REMOTE_PORT',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_ALE_REMOTE_USER_ID',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_ALE_REMOTE_MACHINE_ID',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_IP_DESTINATION_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_FLAGS',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_INTERFACE_TYPE',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN6SP1)
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_INTERFACE_INDEX',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_SUB_INTERFACE_INDEX',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_IP_ARRIVAL_INTERFACE',    
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_ARRIVAL_INTERFACE_TYPE',   
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_ARRIVAL_TUNNEL_TYPE',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_ARRIVAL_INTERFACE_INDEX',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_NEXTHOP_SUB_INTERFACE_INDEX',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_IP_NEXTHOP_INTERFACE',   
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_NEXTHOP_INTERFACE_TYPE',   
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_NEXTHOP_TUNNEL_TYPE',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_NEXTHOP_INTERFACE_INDEX',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_ORIGINAL_PROFILE_ID',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_CURRENT_PROFILE_ID',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_REAUTHORIZE_REASON',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_PEER_NAME',    
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_ORIGINAL_ICMP_TYPE',    
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_INTERFACE_QUARANTINE_EPOCH',    
        #if (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_ALE_ORIGINAL_APP_ID',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_ALE_PACKAGE_ID',   
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_ALE_SECURITY_ATTRIBUTE_FQBN_VALUE',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_ALE_EFFECTIVE_NAME',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN8)
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)   
        #endif // (NTDDI_VERSION >= NTDDI_WIN6SP1)
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_BITMAP_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_BITMAP_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_BITMAP_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_BITMAP_IP_REMOTE_PORT',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V4_MAX'
    ],
    FWPS_LAYER_ALE_AUTH_CONNECT_V6 : [
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_ALE_APP_ID',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_ALE_USER_ID',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_IP_PROTOCOL',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_IP_REMOTE_PORT',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_ALE_REMOTE_USER_ID',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_ALE_REMOTE_MACHINE_ID',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_IP_DESTINATION_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_FLAGS',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_INTERFACE_TYPE',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN6SP1)
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_INTERFACE_INDEX',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_SUB_INTERFACE_INDEX',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_IP_ARRIVAL_INTERFACE',    
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_ARRIVAL_INTERFACE_TYPE',   
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_ARRIVAL_TUNNEL_TYPE',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_ARRIVAL_INTERFACE_INDEX',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_NEXTHOP_SUB_INTERFACE_INDEX',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_IP_NEXTHOP_INTERFACE',   
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_NEXTHOP_INTERFACE_TYPE',   
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_NEXTHOP_TUNNEL_TYPE',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_NEXTHOP_INTERFACE_INDEX',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_ORIGINAL_PROFILE_ID',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_CURRENT_PROFILE_ID',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_REAUTHORIZE_REASON',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_PEER_NAME',  
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_ORIGINAL_ICMP_TYPE',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_INTERFACE_QUARANTINE_EPOCH',    
        #if (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_ALE_ORIGINAL_APP_ID',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_ALE_PACKAGE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_ALE_SECURITY_ATTRIBUTE_FQBN_VALUE',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_ALE_EFFECTIVE_NAME',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN8)
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)  
        #endif // (NTDDI_VERSION >= NTDDI_WIN6SP1)
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_BITMAP_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_BITMAP_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_BITMAP_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_BITMAP_IP_REMOTE_PORT',
        'FWPS_FIELD_ALE_AUTH_CONNECT_V6_MAX'
    ],
    FWPS_LAYER_ALE_AUTH_LISTEN_V4 : [
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_ALE_APP_ID',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_ALE_USER_ID',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_FLAGS',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_INTERFACE_TYPE',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_LOCAL_INTERFACE_PROFILE_ID',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_SIO_FIREWALL_SOCKET_PROPERTY',
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        #if (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_ALE_PACKAGE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_ALE_SECURITY_ATTRIBUTE_FQBN_VALUE',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif //(NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_MAX'
    ],
    FWPS_LAYER_ALE_AUTH_LISTEN_V4_DISCARD : [
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_DISCARD_ALE_APP_ID',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_DISCARD_ALE_USER_ID',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_DISCARD_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_DISCARD_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_DISCARD_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_DISCARD_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_DISCARD_FLAGS',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_DISCARD_INTERFACE_TYPE',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_DISCARD_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_DISCARD_LOCAL_INTERFACE_PROFILE_ID',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_DISCARD_SIO_FIREWALL_SOCKET_PROPERTY',
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        #if (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_DISCARD_ALE_PACKAGE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_DISCARD_ALE_SECURITY_ATTRIBUTE_FQBN_VALUE',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_DISCARD_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif //(NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_AUTH_LISTEN_V4_DISCARD_MAX'
    ],
    FWPS_LAYER_ALE_AUTH_LISTEN_V6 : [
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_ALE_APP_ID',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_ALE_USER_ID',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_FLAGS',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_INTERFACE_TYPE',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_LOCAL_INTERFACE_PROFILE_ID',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_SIO_FIREWALL_SOCKET_PROPERTY',
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        #if (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_ALE_PACKAGE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_ALE_SECURITY_ATTRIBUTE_FQBN_VALUE',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif //(NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_MAX'
    ],
    FWPS_LAYER_ALE_AUTH_LISTEN_V6_DISCARD : [
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_DISCARD_ALE_APP_ID',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_DISCARD_ALE_USER_ID',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_DISCARD_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_DISCARD_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_DISCARD_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_DISCARD_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_DISCARD_FLAGS',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_DISCARD_INTERFACE_TYPE',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_DISCARD_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_DISCARD_LOCAL_INTERFACE_PROFILE_ID',
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_DISCARD_SIO_FIREWALL_SOCKET_PROPERTY',
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        #if (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_DISCARD_ALE_PACKAGE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_DISCARD_ALE_SECURITY_ATTRIBUTE_FQBN_VALUE',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_DISCARD_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif //(NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_AUTH_LISTEN_V6_DISCARD_MAX'
    ],
    FWPS_LAYER_ALE_AUTH_RECV_ACCEPT_V4 : [
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_ALE_APP_ID',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_ALE_USER_ID',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_IP_PROTOCOL',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_IP_REMOTE_PORT',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_ALE_REMOTE_USER_ID',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_ALE_REMOTE_MACHINE_ID',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_FLAGS',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_SIO_FIREWALL_SYSTEM_PORT',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_NAP_CONTEXT',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_INTERFACE_TYPE',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_TUNNEL_TYPE',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_INTERFACE_INDEX',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_SUB_INTERFACE_INDEX',
        #if (NTDDI_VERSION >= NTDDI_WIN6SP1)
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_IP_ARRIVAL_INTERFACE',   
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_ARRIVAL_INTERFACE_TYPE',   
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_ARRIVAL_TUNNEL_TYPE',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_ARRIVAL_INTERFACE_INDEX',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_NEXTHOP_SUB_INTERFACE_INDEX',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_IP_NEXTHOP_INTERFACE',   
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_NEXTHOP_INTERFACE_TYPE',   
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_NEXTHOP_TUNNEL_TYPE',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_NEXTHOP_INTERFACE_INDEX',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_ORIGINAL_PROFILE_ID',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_CURRENT_PROFILE_ID',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_REAUTHORIZE_REASON',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_ORIGINAL_ICMP_TYPE',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_INTERFACE_QUARANTINE_EPOCH',   
        #if (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_ALE_PACKAGE_ID',   
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_ALE_SECURITY_ATTRIBUTE_FQBN_VALUE',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN8)
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        #endif // (NTDDI_VERSION >= NTDDI_WIN6SP1)
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_BITMAP_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_BITMAP_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_BITMAP_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_BITMAP_IP_REMOTE_PORT',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V4_MAX'
    ],
    FWPS_LAYER_ALE_AUTH_RECV_ACCEPT_V6 : [
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_ALE_APP_ID',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_ALE_USER_ID',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_IP_PROTOCOL',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_IP_REMOTE_PORT',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_ALE_REMOTE_USER_ID',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_ALE_REMOTE_MACHINE_ID',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_FLAGS',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_SIO_FIREWALL_SYSTEM_PORT',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_NAP_CONTEXT',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_INTERFACE_TYPE',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_TUNNEL_TYPE',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_INTERFACE_INDEX',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_SUB_INTERFACE_INDEX',
        #if (NTDDI_VERSION >= NTDDI_WIN6SP1)
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_IP_ARRIVAL_INTERFACE',    
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_ARRIVAL_INTERFACE_TYPE',   
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_ARRIVAL_TUNNEL_TYPE',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_ARRIVAL_INTERFACE_INDEX',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_NEXTHOP_SUB_INTERFACE_INDEX',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_IP_NEXTHOP_INTERFACE',   
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_NEXTHOP_INTERFACE_TYPE',   
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_NEXTHOP_TUNNEL_TYPE',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_NEXTHOP_INTERFACE_INDEX',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_ORIGINAL_PROFILE_ID',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_CURRENT_PROFILE_ID',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_REAUTHORIZE_REASON',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_ORIGINAL_ICMP_TYPE',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_INTERFACE_QUARANTINE_EPOCH',    
        #if (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_ALE_PACKAGE_ID',   
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_ALE_SECURITY_ATTRIBUTE_FQBN_VALUE',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN8)
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        #endif // (NTDDI_VERSION >= NTDDI_WIN6SP1)
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_BITMAP_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_BITMAP_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_BITMAP_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_BITMAP_IP_REMOTE_PORT',
        'FWPS_FIELD_ALE_AUTH_RECV_ACCEPT_V6_MAX'
    ],
    FWPS_LAYER_ALE_CONNECT_REDIRECT_V4 : [
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V4_ALE_APP_ID',
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V4_ALE_USER_ID',
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V4_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V4_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V4_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V4_IP_PROTOCOL',
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V4_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V4_IP_DESTINATION_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V4_IP_REMOTE_PORT',
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V4_FLAGS',
        #if (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V4_ALE_ORIGINAL_APP_ID',
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V4_ALE_PACKAGE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V4_ALE_SECURITY_ATTRIBUTE_FQBN_VALUE',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V4_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V4_MAX'
    ],
    FWPS_LAYER_ALE_CONNECT_REDIRECT_V6 : [
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V6_ALE_APP_ID',
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V6_ALE_USER_ID',
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V6_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V6_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V6_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V6_IP_PROTOCOL',
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V6_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V6_IP_DESTINATION_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V6_IP_REMOTE_PORT',
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V6_FLAGS',
        #if (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V6_ALE_ORIGINAL_APP_ID',
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V6_ALE_PACKAGE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V6_ALE_SECURITY_ATTRIBUTE_FQBN_VALUE',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V6_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_CONNECT_REDIRECT_V6_MAX'
    ],
    FWPS_LAYER_ALE_ENDPOINT_CLOSURE_V4 : [
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V4_ALE_APP_ID',
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V4_ALE_USER_ID',
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V4_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V4_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V4_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V4_IP_PROTOCOL',
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V4_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V4_IP_REMOTE_PORT',
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V4_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V4_FLAGS',
        #if (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V4_ALE_PACKAGE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V4_ALE_SECURITY_ATTRIBUTE_FQBN_VALUE',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V4_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif //(NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V4_MAX'
    ],
    FWPS_LAYER_ALE_ENDPOINT_CLOSURE_V6 : [
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V6_ALE_APP_ID',
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V6_ALE_USER_ID',
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V6_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V6_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V6_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V6_IP_PROTOCOL',
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V6_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V6_IP_REMOTE_PORT',
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V6_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V6_FLAGS',
        #if (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V6_ALE_PACKAGE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V6_ALE_SECURITY_ATTRIBUTE_FQBN_VALUE',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V6_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif //(NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_ENDPOINT_CLOSURE_V6_MAX'
    ],
    FWPS_LAYER_ALE_FLOW_ESTABLISHED_V4 : [
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_ALE_APP_ID',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_ALE_USER_ID',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_IP_PROTOCOL',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_IP_REMOTE_PORT',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_ALE_REMOTE_USER_ID',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_ALE_REMOTE_MACHINE_ID',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_IP_DESTINATION_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DIRECTION',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_INTERFACE_TYPE',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN6SP1)
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_FLAGS',
        #if (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_ALE_ORIGINAL_APP_ID',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_ALE_PACKAGE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_ALE_SECURITY_ATTRIBUTE_FQBN_VALUE',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN8)
        #endif // (NTDDI_VERSION >= NTDDI_WIN6SP1)   
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_BITMAP_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_BITMAP_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_BITMAP_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_BITMAP_IP_REMOTE_PORT',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_MAX'
    ],
    FWPS_LAYER_ALE_FLOW_ESTABLISHED_V4_DISCARD : [
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_ALE_APP_ID',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_ALE_USER_ID',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_IP_PROTOCOL',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_IP_REMOTE_PORT',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_ALE_REMOTE_USER_ID',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_ALE_REMOTE_MACHINE_ID',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_IP_DESTINATION_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_DIRECTION',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_INTERFACE_TYPE',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN6SP1)
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_FLAGS',
        #if (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_ALE_ORIGINAL_APP_ID',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_ALE_PACKAGE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_ALE_SECURITY_ATTRIBUTE_FQBN_VALUE',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN8)
        #endif // (NTDDI_VERSION >= NTDDI_WIN6SP1)   
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_BITMAP_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_BITMAP_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_BITMAP_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_BITMAP_IP_REMOTE_PORT',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V4_DISCARD_MAX'
    ],
    FWPS_LAYER_ALE_FLOW_ESTABLISHED_V6 : [
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_ALE_APP_ID',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_ALE_USER_ID',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_IP_PROTOCOL',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_IP_REMOTE_PORT',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_ALE_REMOTE_USER_ID',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_ALE_REMOTE_MACHINE_ID',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_IP_DESTINATION_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DIRECTION',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_INTERFACE_TYPE',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN6SP1)
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_FLAGS',
        #if (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_ALE_ORIGINAL_APP_ID',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_ALE_PACKAGE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_ALE_SECURITY_ATTRIBUTE_FQBN_VALUE',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN8)
        #endif // (NTDDI_VERSION >= NTDDI_WIN6SP1)      
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_BITMAP_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_BITMAP_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_BITMAP_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_BITMAP_IP_REMOTE_PORT',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_MAX'
    ],
    FWPS_LAYER_ALE_FLOW_ESTABLISHED_V6_DISCARD : [
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_ALE_APP_ID',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_ALE_USER_ID',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_IP_PROTOCOL',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_IP_REMOTE_PORT',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_ALE_REMOTE_USER_ID',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_ALE_REMOTE_MACHINE_ID',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_IP_DESTINATION_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_DIRECTION',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_INTERFACE_TYPE',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN6SP1)
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_FLAGS',
        #if (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_ALE_ORIGINAL_APP_ID',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_ALE_PACKAGE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_ALE_SECURITY_ATTRIBUTE_FQBN_VALUE',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN8)
        #endif // (NTDDI_VERSION >= NTDDI_WIN6SP1)      
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_BITMAP_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_BITMAP_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_BITMAP_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_BITMAP_IP_REMOTE_PORT',
        'FWPS_FIELD_ALE_FLOW_ESTABLISHED_V6_DISCARD_MAX'
    ],
    FWPS_LAYER_ALE_RESOURCE_ASSIGNMENT_V4 : [
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_ALE_APP_ID',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_ALE_USER_ID',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_IP_PROTOCOL',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_ALE_PROMISCUOUS_MODE',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_FLAGS',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_INTERFACE_TYPE',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_LOCAL_INTERFACE_PROFILE_ID',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_SIO_FIREWALL_SOCKET_PROPERTY',
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        #if (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_ALE_PACKAGE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_ALE_SECURITY_ATTRIBUTE_FQBN_VALUE',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif //(NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_BITMAP_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_BITMAP_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_MAX'
    ],
    FWPS_LAYER_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD : [
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD_ALE_APP_ID',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD_ALE_USER_ID',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD_IP_PROTOCOL',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD_ALE_PROMISCUOUS_MODE',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD_FLAGS',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD_INTERFACE_TYPE',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD_LOCAL_INTERFACE_PROFILE_ID',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD_SIO_FIREWALL_SOCKET_PROPERTY',
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        #if (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD_ALE_PACKAGE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD_ALE_SECURITY_ATTRIBUTE_FQBN_VALUE',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif //(NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD_BITMAP_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD_BITMAP_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V4_DISCARD_MAX'
    ],
    FWPS_LAYER_ALE_RESOURCE_ASSIGNMENT_V6 : [
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_ALE_APP_ID',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_ALE_USER_ID',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_IP_PROTOCOL',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_ALE_PROMISCUOUS_MODE',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_FLAGS',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_INTERFACE_TYPE',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_LOCAL_INTERFACE_PROFILE_ID',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_SIO_FIREWALL_SOCKET_PROPERTY',
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        #if (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_ALE_PACKAGE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_ALE_SECURITY_ATTRIBUTE_FQBN_VALUE',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif //(NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_BITMAP_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_BITMAP_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_MAX'
    ],
    FWPS_LAYER_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD : [
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD_ALE_APP_ID',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD_ALE_USER_ID',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD_IP_PROTOCOL',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD_ALE_PROMISCUOUS_MODE',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD_FLAGS',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD_INTERFACE_TYPE',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD_LOCAL_INTERFACE_PROFILE_ID',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD_SIO_FIREWALL_SOCKET_PROPERTY',
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        #if (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD_ALE_PACKAGE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD_ALE_SECURITY_ATTRIBUTE_FQBN_VALUE',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif //(NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN8)
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD_BITMAP_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD_BITMAP_IP_LOCAL_PORT',
        'FWPS_FIELD_ALE_RESOURCE_ASSIGNMENT_V6_DISCARD_MAX'
    ],
    FWPS_LAYER_DATAGRAM_DATA_V4 : [
        'FWPS_FIELD_DATAGRAM_DATA_V4_IP_PROTOCOL',
        'FWPS_FIELD_DATAGRAM_DATA_V4_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_DATAGRAM_DATA_V4_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_DATAGRAM_DATA_V4_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_DATAGRAM_DATA_V4_IP_LOCAL_PORT',
        'FWPS_FIELD_DATAGRAM_DATA_V4_IP_REMOTE_PORT',
        'FWPS_FIELD_DATAGRAM_DATA_V4_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_DATAGRAM_DATA_V4_INTERFACE_INDEX',
        'FWPS_FIELD_DATAGRAM_DATA_V4_SUB_INTERFACE_INDEX',
        'FWPS_FIELD_DATAGRAM_DATA_V4_DIRECTION',
        'FWPS_FIELD_DATAGRAM_DATA_V4_FLAGS',
        'FWPS_FIELD_DATAGRAM_DATA_V4_INTERFACE_TYPE',
        'FWPS_FIELD_DATAGRAM_DATA_V4_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_DATAGRAM_DATA_V4_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_DATAGRAM_DATA_V4_MAX'
    ],
    FWPS_LAYER_DATAGRAM_DATA_V6 : [
        'FWPS_FIELD_DATAGRAM_DATA_V6_IP_PROTOCOL',
        'FWPS_FIELD_DATAGRAM_DATA_V6_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_DATAGRAM_DATA_V6_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_DATAGRAM_DATA_V6_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_DATAGRAM_DATA_V6_IP_LOCAL_PORT',
        'FWPS_FIELD_DATAGRAM_DATA_V6_IP_REMOTE_PORT',
        'FWPS_FIELD_DATAGRAM_DATA_V6_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_DATAGRAM_DATA_V6_INTERFACE_INDEX',
        'FWPS_FIELD_DATAGRAM_DATA_V6_SUB_INTERFACE_INDEX',
        'FWPS_FIELD_DATAGRAM_DATA_V6_DIRECTION',
        'FWPS_FIELD_DATAGRAM_DATA_V6_FLAGS',
        'FWPS_FIELD_DATAGRAM_DATA_V6_INTERFACE_TYPE',
        'FWPS_FIELD_DATAGRAM_DATA_V6_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_DATAGRAM_DATA_V6_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_DATAGRAM_DATA_V6_MAX'
    ],
    FWPS_LAYER_INBOUND_ICMP_ERROR_V4 : [
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_EMBEDDED_PROTOCOL',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_EMBEDDED_REMOTE_ADDRESS',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_EMBEDDED_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_EMBEDDED_LOCAL_PORT',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_EMBEDDED_REMOTE_PORT',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_ICMP_TYPE',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_ICMP_CODE',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_INTERFACE_INDEX',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_SUB_INTERFACE_INDEX',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_INTERFACE_TYPE',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN6SP1)
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_IP_ARRIVAL_INTERFACE',   
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_ARRIVAL_INTERFACE_INDEX',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_ARRIVAL_INTERFACE_TYPE',   
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_ARRIVAL_TUNNEL_TYPE',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_FLAGS',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_ARRIVAL_INTERFACE_PROFILE_ID',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_INTERFACE_QUARANTINE_EPOCH',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        #endif // (NTDDI_VERSION >= NTDDI_WIN6SP1)
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V4_MAX'
    ],
    FWPS_LAYER_INBOUND_ICMP_ERROR_V6 : [
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_EMBEDDED_PROTOCOL',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_EMBEDDED_REMOTE_ADDRESS',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_EMBEDDED_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_EMBEDDED_LOCAL_PORT',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_EMBEDDED_REMOTE_PORT',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_ICMP_TYPE',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_ICMP_CODE',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_INTERFACE_INDEX',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_SUB_INTERFACE_INDEX',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_INTERFACE_TYPE',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN6SP1)   
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_IP_ARRIVAL_INTERFACE',   
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_ARRIVAL_INTERFACE_INDEX',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_ARRIVAL_INTERFACE_TYPE',   
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_ARRIVAL_TUNNEL_TYPE',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_FLAGS',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_ARRIVAL_INTERFACE_PROFILE_ID',
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_INTERFACE_QUARANTINE_EPOCH',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        #endif // (NTDDI_VERSION >= NTDDI_WIN6SP1)
        'FWPS_FIELD_INBOUND_ICMP_ERROR_V6_MAX'
    ],
    FWPS_LAYER_INBOUND_TRANSPORT_V4 : [
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_IP_PROTOCOL',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_IP_LOCAL_PORT',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_IP_REMOTE_PORT',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_INTERFACE_INDEX',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_SUB_INTERFACE_INDEX',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_FLAGS',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_INTERFACE_TYPE',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_PROFILE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_IPSEC_SECURITY_REALM_ID',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_MAX'
    ],
    FWPS_LAYER_INBOUND_TRANSPORT_V4_DISCARD : [
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_DISCARD_IP_PROTOCOL',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_DISCARD_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_DISCARD_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_DISCARD_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_DISCARD_IP_LOCAL_PORT',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_DISCARD_IP_REMOTE_PORT',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_DISCARD_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_DISCARD_INTERFACE_INDEX',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_DISCARD_SUB_INTERFACE_INDEX',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_DISCARD_FLAGS',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_DISCARD_INTERFACE_TYPE',
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_DISCARD_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_DISCARD_PROFILE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_DISCARD_IPSEC_SECURITY_REALM_ID',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_DISCARD_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_INBOUND_TRANSPORT_V4_DISCARD_MAX'
    ],
    FWPS_LAYER_INBOUND_TRANSPORT_V6 : [
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_IP_PROTOCOL',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_IP_LOCAL_PORT',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_IP_REMOTE_PORT',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_INTERFACE_INDEX',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_SUB_INTERFACE_INDEX',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_FLAGS',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_INTERFACE_TYPE',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_PROFILE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_IPSEC_SECURITY_REALM_ID',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_MAX'
    ],
    FWPS_LAYER_INBOUND_TRANSPORT_V6_DISCARD : [
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_DISCARD_IP_PROTOCOL',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_DISCARD_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_DISCARD_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_DISCARD_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_DISCARD_IP_LOCAL_PORT',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_DISCARD_IP_REMOTE_PORT',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_DISCARD_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_DISCARD_INTERFACE_INDEX',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_DISCARD_SUB_INTERFACE_INDEX',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_DISCARD_FLAGS',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_DISCARD_INTERFACE_TYPE',
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_DISCARD_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_DISCARD_PROFILE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_DISCARD_IPSEC_SECURITY_REALM_ID',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_DISCARD_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_INBOUND_TRANSPORT_V6_DISCARD_MAX'
    ],
    FWPS_LAYER_IPFORWARD_V4 : [
        'FWPS_FIELD_IPFORWARD_V4_IP_SOURCE_ADDRESS',
        'FWPS_FIELD_IPFORWARD_V4_IP_DESTINATION_ADDRESS',
        'FWPS_FIELD_IPFORWARD_V4_IP_DESTINATION_ADDRESS_TYPE',
        'FWPS_FIELD_IPFORWARD_V4_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_IPFORWARD_V4_IP_FORWARD_INTERFACE',
        'FWPS_FIELD_IPFORWARD_V4_SOURCE_INTERFACE_INDEX',
        'FWPS_FIELD_IPFORWARD_V4_SOURCE_SUB_INTERFACE_INDEX',
        'FWPS_FIELD_IPFORWARD_V4_DESTINATION_INTERFACE_INDEX',
        'FWPS_FIELD_IPFORWARD_V4_DESTINATION_SUB_INTERFACE_INDEX',
        'FWPS_FIELD_IPFORWARD_V4_FLAGS',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_IPFORWARD_V4_IP_PHYSICAL_ARRIVAL_INTERFACE',
        'FWPS_FIELD_IPFORWARD_V4_ARRIVAL_INTERFACE_PROFILE_ID',
        'FWPS_FIELD_IPFORWARD_V4_IP_PHYSICAL_NEXTHOP_INTERFACE',
        'FWPS_FIELD_IPFORWARD_V4_NEXTHOP_INTERFACE_PROFILE_ID',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_IPFORWARD_V4_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_IPFORWARD_V4_MAX'
    ],
    FWPS_LAYER_IPFORWARD_V6 : [
        'FWPS_FIELD_IPFORWARD_V6_IP_SOURCE_ADDRESS',
        'FWPS_FIELD_IPFORWARD_V6_IP_DESTINATION_ADDRESS',
        'FWPS_FIELD_IPFORWARD_V6_IP_DESTINATION_ADDRESS_TYPE',
        'FWPS_FIELD_IPFORWARD_V6_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_IPFORWARD_V6_IP_FORWARD_INTERFACE',
        'FWPS_FIELD_IPFORWARD_V6_SOURCE_INTERFACE_INDEX',
        'FWPS_FIELD_IPFORWARD_V6_SOURCE_SUB_INTERFACE_INDEX',
        'FWPS_FIELD_IPFORWARD_V6_DESTINATION_INTERFACE_INDEX',
        'FWPS_FIELD_IPFORWARD_V6_DESTINATION_SUB_INTERFACE_INDEX',
        'FWPS_FIELD_IPFORWARD_V6_FLAGS',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_IPFORWARD_V6_IP_PHYSICAL_ARRIVAL_INTERFACE',
        'FWPS_FIELD_IPFORWARD_V6_ARRIVAL_INTERFACE_PROFILE_ID',
        'FWPS_FIELD_IPFORWARD_V6_IP_PHYSICAL_NEXTHOP_INTERFACE',
        'FWPS_FIELD_IPFORWARD_V6_NEXTHOP_INTERFACE_PROFILE_ID',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_IPFORWARD_V6_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_IPFORWARD_V6_MAX'
    ],
    FWPS_LAYER_OUTBOUND_ICMP_ERROR_V4 : [
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V4_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V4_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V4_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V4_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V4_ICMP_TYPE',
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V4_ICMP_CODE',
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V4_INTERFACE_INDEX',
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V4_SUB_INTERFACE_INDEX',
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V4_INTERFACE_TYPE',
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V4_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN6SP1)
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V4_FLAGS',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V4_NEXTHOP_INTERFACE_PROFILE_ID',
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V4_INTERFACE_QUARANTINE_EPOCH',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V4_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        #endif // (NTDDI_VERSION >= NTDDI_WIN6SP1)
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V4_MAX'
    ],
    FWPS_LAYER_OUTBOUND_ICMP_ERROR_V6 : [
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V6_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V6_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V6_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V6_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V6_IP_LOCAL_PORT',
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V6_IP_REMOTE_PORT',
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V6_INTERFACE_INDEX',
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V6_SUB_INTERFACE_INDEX',
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V6_INTERFACE_TYPE',
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V6_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN6SP1)
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V6_FLAGS',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V6_NEXTHOP_INTERFACE_PROFILE_ID',
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V6_INTERFACE_QUARANTINE_EPOCH',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V6_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        #endif // (NTDDI_VERSION >= NTDDI_WIN6SP1)
        'FWPS_FIELD_OUTBOUND_ICMP_ERROR_V6_MAX'
    ],
    FWPS_LAYER_OUTBOUND_TRANSPORT_V4 : [
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V4_IP_PROTOCOL',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V4_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V4_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V4_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V4_IP_LOCAL_PORT',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V4_IP_REMOTE_PORT',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V4_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V4_INTERFACE_INDEX',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V4_SUB_INTERFACE_INDEX',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V4_IP_DESTINATION_ADDRESS_TYPE',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V4_FLAGS',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V4_INTERFACE_TYPE',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V4_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V4_PROFILE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V4_IPSEC_SECURITY_REALM_ID',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V4_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V4_MAX'
    ],
    FWPS_LAYER_OUTBOUND_TRANSPORT_V6 : [
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V6_IP_PROTOCOL',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V6_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V6_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V6_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V6_IP_LOCAL_PORT',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V6_IP_REMOTE_PORT',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V6_IP_LOCAL_INTERFACE',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V6_INTERFACE_INDEX',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V6_SUB_INTERFACE_INDEX',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V6_IP_DESTINATION_ADDRESS_TYPE',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V6_FLAGS',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V6_INTERFACE_TYPE',
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V6_TUNNEL_TYPE',
        #if (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V6_PROFILE_ID',
        #if (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V6_IPSEC_SECURITY_REALM_ID',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V6_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WINTHRESHOLD)
        #endif // (NTDDI_VERSION >= NTDDI_WIN7)
        'FWPS_FIELD_OUTBOUND_TRANSPORT_V6_MAX'
    ],
    FWPS_LAYER_STREAM_V4 : [
        'FWPS_FIELD_STREAM_V4_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_STREAM_V4_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_STREAM_V4_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_STREAM_V4_IP_LOCAL_PORT',
        'FWPS_FIELD_STREAM_V4_IP_REMOTE_PORT',
        'FWPS_FIELD_STREAM_V4_DIRECTION',
        #if (NTDDI_VERSION >= NTDDI_WIN6SP1)
        'FWPS_FIELD_STREAM_V4_FLAGS',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_STREAM_V4_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WIN6SP1)         
        'FWPS_FIELD_STREAM_V4_MAX'
    ],
    FWPS_LAYER_STREAM_V6 : [
        'FWPS_FIELD_STREAM_V6_IP_LOCAL_ADDRESS',
        'FWPS_FIELD_STREAM_V6_IP_LOCAL_ADDRESS_TYPE',
        'FWPS_FIELD_STREAM_V6_IP_REMOTE_ADDRESS',
        'FWPS_FIELD_STREAM_V6_IP_LOCAL_PORT',
        'FWPS_FIELD_STREAM_V6_IP_REMOTE_PORT',
        'FWPS_FIELD_STREAM_V6_DIRECTION',
        #if (NTDDI_VERSION >= NTDDI_WIN6SP1)
        'FWPS_FIELD_STREAM_V6_FLAGS',
        #if (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        'FWPS_FIELD_STREAM_V6_COMPARTMENT_ID',
        #endif // (NTDDI_VERSION >= NTDDI_WIN10_RS2)
        #endif // (NTDDI_VERSION >= NTDDI_WIN6SP1)    
        'FWPS_FIELD_STREAM_V6_MAX'
    ]
}

FWP_ACTION_FLAG_TERMINATING         = 0x00001000
FWP_ACTION_FLAG_NON_TERMINATING     = 0x00002000
FWP_ACTION_FLAG_CALLOUT             = 0x00004000
FWP_ACTION_BLOCK                    = 0x00000001 | FWP_ACTION_FLAG_TERMINATING
FWP_ACTION_PERMIT                   = 0x00000002 | FWP_ACTION_FLAG_TERMINATING
FWP_ACTION_CALLOUT_TERMINATING      = 0x00000003 | FWP_ACTION_FLAG_CALLOUT | FWP_ACTION_FLAG_TERMINATING
FWP_ACTION_CALLOUT_INSPECTION       = 0x00000004 | FWP_ACTION_FLAG_CALLOUT | FWP_ACTION_FLAG_NON_TERMINATING
FWP_ACTION_CALLOUT_UNKNOWN          = 0x00000005 | FWP_ACTION_FLAG_CALLOUT
FWP_ACTION_CONTINUE                 = 0x00000006 | FWP_ACTION_FLAG_NON_TERMINATING
FWP_ACTION_NONE                     = 0x00000007
FWP_ACTION_NONE_NO_MATCH            = 0x00000008
FWP_ACTION_BITMAP_INDEX_SET         = 0x00000009

actionType_to_str = {
    FWP_ACTION_FLAG_TERMINATING         : 'FWP_ACTION_FLAG_TERMINATING',
    FWP_ACTION_FLAG_NON_TERMINATING     : 'FWP_ACTION_FLAG_NON_TERMINATING',
    FWP_ACTION_FLAG_CALLOUT             : 'FWP_ACTION_FLAG_CALLOUT',
    FWP_ACTION_BLOCK                    : 'FWP_ACTION_BLOCK',
    FWP_ACTION_PERMIT                   : 'FWP_ACTION_PERMIT',
    FWP_ACTION_CALLOUT_TERMINATING      : 'FWP_ACTION_CALLOUT_TERMINATING',
    FWP_ACTION_CALLOUT_INSPECTION       : 'FWP_ACTION_CALLOUT_INSPECTION',
    FWP_ACTION_CALLOUT_UNKNOWN          : 'FWP_ACTION_CALLOUT_UNKNOWN',
    FWP_ACTION_CONTINUE                 : 'FWP_ACTION_CONTINUE',
    FWP_ACTION_NONE                     : 'FWP_ACTION_NONE',
    FWP_ACTION_NONE_NO_MATCH            : 'FWP_ACTION_NONE_NO_MATCH',
    FWP_ACTION_BITMAP_INDEX_SET         : 'FWP_ACTION_BITMAP_INDEX_SET'
}

FWP_MATCH_EQUAL                     = 0
FWP_MATCH_GREATER                   = 1
FWP_MATCH_LESS                      = 2
FWP_MATCH_GREATER_OR_EQUAL          = 3
FWP_MATCH_LESS_OR_EQUAL             = 4
FWP_MATCH_RANGE                     = 5
FWP_MATCH_FLAGS_ALL_SET             = 6
FWP_MATCH_FLAGS_ANY_SET             = 7
FWP_MATCH_FLAGS_NONE_SET            = 8
FWP_MATCH_EQUAL_CASE_INSENSITIVE    = 9
FWP_MATCH_NOT_EQUAL                 = 10
FWP_MATCH_PREFIX                    = 11
FWP_MATCH_NOT_PREFIX                = 12
FWP_MATCH_TYPE_MAX                  = 13

matchType_to_str = [
    'FWP_MATCH_EQUAL',
    'FWP_MATCH_GREATER',
    'FWP_MATCH_LESS',
    'FWP_MATCH_GREATER_OR_EQUAL',
    'FWP_MATCH_LESS_OR_EQUAL',
    'FWP_MATCH_RANGE',
    'FWP_MATCH_FLAGS_ALL_SET',
    'FWP_MATCH_FLAGS_ANY_SET',
    'FWP_MATCH_FLAGS_NONE_SET',
    'FWP_MATCH_EQUAL_CASE_INSENSITIVE',
    'FWP_MATCH_NOT_EQUAL',
    'FWP_MATCH_PREFIX',
    'FWP_MATCH_NOT_PREFIX'
]

FWP_EMPTY               = 0
FWP_UINT8               = 1
FWP_UINT16              = 2
FWP_UINT32              = 3
FWP_UINT64              = 4
FWP_BYTE_ARRAY16_TYPE   = 11
FWP_BYTE_BLOB_TYPE      = 12
FWP_SID                 = 13
FWP_RANGE_TYPE          = 258

FWPM_FILTER_FLAG_HAS_PROVIDER_CONTEXT   = 0x00000004

def format_hex(s):
    return ":".join("{:02x}".format(ord(c)) for c in s)

def signed_long_at(f):
    return struct.unpack('l', f.read(4))[0]

def unsigned_char_at(f):
    return struct.unpack('B', f.read(1))[0]

def unsigned_short_at(f):
    return struct.unpack('H', f.read(2))[0]

def unsigned_long_at(f):
    return struct.unpack('L', f.read(4))[0]

def unsigned_long_long_at(f):
    return struct.unpack('Q', f.read(8))[0]

def test_unsigned_short_at(f):
    x = struct.unpack('H', f.read(2))[0]
    f.seek(-2, 1)
    return x

def test_unsigned_long_at(f):
    x = struct.unpack('L', f.read(4))[0]
    f.seek(-4, 1)
    return x
